version: 2

refs:
  container: &container
    docker:
      - image: node:16
    working_directory: ~/repo
  steps:
    - &Versions
      run:
        name: Versions
        command: node -v && npm -v && yarn -v
    - &Install
      run:
        name: Install Dependencies
        command: yarn install --pure-lockfile
    - &Build
      run:
        name: Build
        command: yarn build
    - &Lint
      run:
        name: Run linter
        command: yarn lint
    - &Test_Unit
      run:
        name: Test - Unit tests
        command: yarn test:ci
    - &Test_CLI_Pointer
      run:
        name: "Test - CLI: json_pointer"
        command: yarn test:pointer
    - &Test_CLI_Patch
      run:
        name: "Test - CLI: json-patch"
        command: yarn test:patch
    - &Test_CLI_Pack
      run:
        name: "Test - CLI: json-pack"
        command: yarn test:pack
    - &Test_E2E_Reactive_RPC
      run:
        name: "Test - E2E: Reactive-RPC"
        command: yarn test:reactive-rpc
    - &Test_Demos
      run:
        name: "Test - Demos can execute"
        command: yarn demo:json-patch && yarn demo:json-pointer && yarn demo:json-rx
    - &Post_to_dev_null
      run:
        name: 'Post to Slack #dev-null'
        command: npx ci-scripts slack --channel="dev-null"

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Install
      - *Lint
      - *Build
      - *Test_Unit
      - *Test_CLI_Pointer
      - *Test_CLI_Patch
      - *Test_CLI_Pack
      - *Test_E2E_Reactive_RPC
      - *Test_Demos
      - *Post_to_dev_null

  master:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Install
      - *Lint
      - *Build
      - *Test_Unit
      - *Test_CLI_Pointer
      - *Test_CLI_Patch
      - *Test_CLI_Pack
      - *Test_E2E_Reactive_RPC
      - *Test_Demos
      - *Post_to_dev_null
      - run:
          name: Release
          command: yarn release
      - *Post_to_dev_null

  nightly:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Install
      - *Lint
      - *Build
      - *Test_Unit
      - *Test_CLI_Pointer
      - *Test_CLI_Patch
      - *Test_CLI_Pack
      - *Test_E2E_Reactive_RPC
      - *Test_Demos
      - *Post_to_dev_null
      - run:
          name: Post to Slack on FAILURE
          command: npx ci slack --channel="dev" --text="** nightly build failed :scream:" --icon_emoji=tired_face
          when: on_fail

workflows:
  version: 2
  all:
    jobs:
      - all:
          context: common-env-vars
          filters:
            branches:
              ignore:
                - master
                - gh-pages
  master:
    jobs:
      - master:
          context: common-env-vars
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: '0 1 * * *'
          filters:
            branches:
              only: master
    jobs:
      - nightly:
          context: common-env-vars
